services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./public:/var/www/html:Z
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: symmetry
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql:Z
    environment:
      MYSQL_DATABASE: symmetry
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    restart: always
    ports:
      - "3306:3306"
