services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      # This only mounts the current working dir to the WP plugin dir.
      # This means that all other WP files are copied everytime after docker-compose down.
      - ./theme_name:/var/www/html/wp-content/themes/theme-name/
      - ./plugin_name:/var/www/html/wp-content/plugins/plugin-name/
      # Remove dev dirs from the theme.
      - ./theme_name/src:/var/www/html/wp-content/themes/theme-name/src/
      - ./theme_name/node_modules:/var/www/html/wp-content/themes/theme-name/node_modules/
      # Remove dev dirs from the plugin.
      - ./plugin_name/src:/var/www/html/wp-content/plugins/plugin-name/src/
      - ./plugin_name/node_modules:/var/www/html/wp-content/plugins/plugin-name/node_modules/
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: symmetry
    restart: always
    depends_on:
      - mysql
    ports:
      - 80:80

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: symmetry
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: always
    ports:
      - 3306:3306

volumes:
  mysql:
